ogi02/Odyssey

odyssey/api/client/package-lock.json, odyssey/api/client/src/App.svelte, odyssey/api/client/src/Authentication/BecomeCreator.svelte, odyssey/api/client/src/Profiles/Profile.svelte, odyssey/api/client/src/Profiles/Profile.svlt, odyssey/api/creatorSpecific.py, odyssey/api/info.py, odyssey/api/main.py, odyssey/api/user.py
- Added responsive design for profile page
- Fixed the problems we had earlier with nested objects in Profile.svelte
- All find functions for getting data from Mongo now return json serializable values
=> Profile page

odyssey/client/src/Authentication/Authentication.svelte, odyssey/client/src/Authentication/authentication_helpers.js, odyssey/client/src/Authentication/authentication_management.js, odyssey/client/src/Profiles/EditProfile.svelte, odyssey/client/src/Profiles/Profile.svelte, odyssey/main.py
- Added functionality for change email and password in Flask and Svelte.
- Reactive input validation and error displaying.
=> Change email and password

odyssey/client/src/Authentication/authentication_management.js
- Upon clicking register input is checked once more, since we found a way to exploit current security
=> [Fix] Checks input once more before registering user in order to avoid possible errors

odyssey/client/package-lock.json, odyssey/flask_classes/post.py, odyssey/flask_classes/tier.py, odyssey/flask_post/post_actions.py, odyssey/main.py
Added posts:
- added all functionality in DB
- flask blueprints with every function
- waiting for svelte implementaition
=> Posts - Only Mongo and Flask

odyssey/flask_authentication/authentication.py, odyssey/flask_classes/user.py, odyssey/flask_profile/profile.py, odyssey/main.py, odyssey/tests/test_authentication.py
- Test database is set up
- Tests for authentication - register (1 valid, 2 invalid), login (1 valid, 2 invalid), logout (1 valid)
- Database is restored after authentication tests
=> Authentication unit tests

odyssey/flask_validators/email_validator.py, odyssey/flask_validators/username_validator.py, odyssey/tests/test_validators.py
- Validators are used to check if a username/email is already taken on registration
- 2 tests for username (1 returns true, 1 false)
- 2 tests for email (1 returns true, 1 false)
=> Validators tests

odyssey/flask_authentication/authentication.py, odyssey/flask_classes/info.py, odyssey/flask_creator/become_creator.py, odyssey/flask_follow/follow.py, odyssey/tests/test_authentication.py, odyssey/tests/test_edit_profile.py, odyssey/tests/test_follow.py, odyssey/tests/test_validators.py
Tests for follow, unfollow and is_following functions
After discussions we decided that Info for user should be created empty on registration, so that the user can follow and become donator, without actually being a creator himself. Info is updated on becoming a creator.
=> [TS-2] Follow tests

odyssey/client/src/Profiles/MyProfile.svelte, odyssey/client/src/Profiles/UserProfile.svelte, odyssey/flask_classes/user.py, odyssey/flask_profile/profile.py
Updated 'is_creator' field in user.py to 'roles' 
- currently 2 roles avaliable:
- user
- creator
- more scalability
- future admin role
=> [BE-9] Update Roles Field in MongoDB

odyssey/flask_classes/creator_specific.py, odyssey/flask_classes/tier.py, odyssey/flask_creator/become_creator.py, odyssey/flask_tier/tier_actions.py, odyssey/tests/test_authentication.py, odyssey/tests/test_edit_profile.py, odyssey/tests/test_follow.py, odyssey/tests/test_tiers.py, odyssey/tests/test_validators.py
Test all tier functionalities from back-end:
- become creator
- create tier
- subscribe to tier
- unsubscribe to tier
=> [TS-2] Tier Tests

odyssey/client/src/Authentication/Authentication.svelte, odyssey/client/src/Helpers/Error.svelte, odyssey/client/src/Helpers/Field.svelte, odyssey/client/src/js/helpers.js, odyssey/flask_validators/email_validator.py, odyssey/flask_validators/username_validator.py, odyssey/tests/test_validators.py
Create a new and improved UI for login and registration.
- Fixed loader icon
- Fixed duplicate messages for username/email
=> [FE-16] New UI for Login and Registration

odyssey/Pipfile, odyssey/Pipfile.lock, odyssey/flask_classes/post.py, odyssey/flask_post/post_actions.py, odyssey/tests/test_posts.py
Added tests for posts only (Every test will be a separate pull request)
Added 10 tests in total
=> [TS-3] Tests for posts, surveys, giveaways, commissions

odyssey/client/src/Profiles/UserProfile.svelte, odyssey/client/src/Surveys/MySurveys.svelte
Fixed wrong percentage in surveys on my profile and other users' profiles
=> [Fix] Fixed wrong percentage on surveys

odyssey/client/src/Giveaways/UserGiveaways.svelte, odyssey/client/src/Posts/UserPosts.svelte, odyssey/client/src/Profiles/UserProfile.svelte, odyssey/client/src/Profiles/profile_management.js, odyssey/client/src/Surveys/UserSurveys.svelte, odyssey/client/src/Tiers/UserTiers.svelte, odyssey/flask_classes/survey.py
Splitted UserProfile.svelte into separate files for the different creator's events:
- user tiers
- user posts
- user surveys
- user giveaways
=> [FE-18] Feed for My Profile and User Profile

odyssey/client/src/Tiers/CreateTier.svelte, odyssey/client/src/Tiers/MyTiers.svelte, odyssey/client/src/Tiers/UserTiers.svelte, odyssey/flask_classes/tier.py, odyssey/flask_validators/tier_name_validator.py, odyssey/flask_validators/tier_price_validator.py, odyssey/main.py
Add real time error handling for tier name and tier price. Tier name is mandatory and should be different than all other tier names for the user. Tier price is mandatory and should be different than all other tier prices for the user. Also tier price is limited between 1 and 1000
=> [FE-17] Error handling for Create Tier form

odyssey/client/src/Profiles/MyProfile.svelte, odyssey/client/src/Profiles/UserProfile.svelte
Since the Commissions feature would require a lot more work than expected, it is left in the backlog of the Ora board and will be addressed after the presentation for Milestone 3.
=> [Fix] Removed Commissions tab

odyssey/client/src/Tiers/CreateTier.svelte
Finished UI and code styling/formatting on Create Tier form. Added Cancel button if the user doesn't want to create a new form.
=> [FE-19] Update UI on all forms (Create Tier form)

odyssey/client/src/Posts/CreatePost.svelte
Finished UI on code styling/formatting for Create Post form. Added Cancel button if user doesn't want to create post. Added Remove photo button if user wants to remove the uploaded photo. Better styling of the Upload button.
=> [FE-19] Update UI on all forms (Create Post form)

odyssey/client/src/Home.svelte, odyssey/client/src/Navigation/NavBar.svelte, odyssey/client/src/Navigation/Search.svelte
Fixed navbar and the search bar has been updated
==================
- added real info in fields
- removed lorem ipsum...
- added footer
- created custom pattern to spice up things
=> [FE-24] Update Navbar and Homepage

odyssey/client/src/Profiles/MyProfile.svelte, odyssey/client/src/Profiles/UserProfile.svelte
Finished UI and code styling/formatting on User Profile. Fixed social media links for creators. Display bio and country of a creator. Minor CSS fix for cover picture for My Profile and User Profile.
> Tests have not passed, because the two commits were too close one to another in time and they interfered between each other, which caused some tests to fail. Pushed the second commit again and all tests passed.
=> [FE-19] Update UI on all forms (User Profile)

odyssey/client/src/Giveaways/CreateGiveaway.svelte
Finished UI and code styling/formatting for Create Giveaway form. Added delete file button if user wants to remove uploaded file. Added cancel button if user doesn't want to create a giveaway.
=> [FE-19] Update UI on all forms (Create Giveaway)

odyssey/client/src/Surveys/CreateSurvey.svelte
Finished UI and code styling/formatting for Create Survey form. Added delete file button if user wants to remove uploaded file. Added cancel button if user doesn't want to create a survey.
=> [FE-19] Update UI on all forms (Create Survey)

odyssey/database_config.py, odyssey/flask_checks/user_checks.py, odyssey/flask_classes/creator_specific.py, odyssey/flask_classes/giveaway.py, odyssey/flask_classes/info.py, odyssey/flask_classes/post.py, odyssey/flask_classes/survey.py, odyssey/flask_classes/tier.py, odyssey/flask_classes/user.py, odyssey/main.py, odyssey/tests/test_authentication.py, odyssey/tests/test_edit_profile.py, odyssey/tests/test_follow.py, odyssey/tests/test_posts.py, odyssey/tests/test_tiers.py, odyssey/tests/test_validators.py
Create a database config file that stores database urls as constants.
Import those constants in all classes in tests, so that they use the name of the constant rather than the database url. Know if you want to change the database url, you need to change it only in the database config file.
=> [BE-11] Constant URLs for Databases

odyssey/client/src/Authentication/BecomeCreator.svelte
Edit the UI of Become Creator form
- Centralised
- Matching colour palette with the other forms
- Fix all pages
=> [FE-23] Become Creator UI
